Repository hyperspy/rosettasciio, pull requests merged in 2022-11, with the labels that each got.

#59 Doc and import improvement #2
  docs/supported_formats/blockfile.rst
  docs/supported_formats/bruker.rst
  docs/supported_formats/digitalsurf.rst
  docs/supported_formats/semper.rst
  docs/supported_formats/tiff.rst
  docs/supported_formats/tvips.rst
  docs/supported_formats/usid.rst
  docs/supported_formats/zspy.rst
  rsciio/__init__.py
  rsciio/blockfile/_api.py
  rsciio/bruker/__init__.py
  rsciio/bruker/_api.py
  rsciio/docstrings.py
  rsciio/semper_unf/__init__.py
  rsciio/semper_unf/_api.py
  rsciio/sur/__init__.py
  rsciio/sur/_api.py
  rsciio/sur/specifications.yaml
  rsciio/tests/test_import.py
  rsciio/tests/test_tiff.py
  rsciio/tests/test_tvips.py
  rsciio/tiff/__init__.py
  rsciio/tiff/_api.py
  rsciio/tvips/__init__.py
  rsciio/tvips/_api.py
  rsciio/usid_hdf5/__init__.py
  rsciio/usid_hdf5/_api.py
  rsciio/zspy/__init__.py
  rsciio/zspy/_api.py
Labels: status: needs review, affects: documentation

#28 activate additional queries
  .github/workflows/codeql.yml
  rsciio/_hierarchical.py
  rsciio/blockfile/_api.py
  rsciio/bruker/_api.py
  rsciio/digital_micrograph/api.py
  rsciio/emd/api.py
  rsciio/empad/api.py
  rsciio/hspy/api.py
  rsciio/jeol/api.py
  rsciio/msa/api.py
  rsciio/netcdf/api.py
  rsciio/phenom/api.py
  rsciio/protochips/api.py
  rsciio/prz/api.py
  rsciio/ripple/api.py
  rsciio/sur/_api.py
  rsciio/tests/test_dm3.py
  rsciio/tests/test_edax.py
  rsciio/tests/test_empad.py
  rsciio/tests/test_image.py
  rsciio/tests/test_import.py
  rsciio/tests/test_jobin_yvon.py
  rsciio/tests/test_mrcz.py
  rsciio/tests/test_nexus_hdf.py
  rsciio/tests/test_ripple.py
  rsciio/tests/test_tiff.py
  rsciio/tests/test_zspy.py
  rsciio/tiff/_api.py
  rsciio/tvips/_api.py
  rsciio/utils/date_time_tools.py
  rsciio/utils/tools.py
  rsciio/zspy/_api.py
Labels: status: needs review, type: maintenance

#58 Bugfix function argument mismatch when reading *.eds files
  rsciio/jeol/api.py
  rsciio/tests/jeol_seq_eds_files.zip
  rsciio/tests/test_jeol.py
Labels: status: needs review, type: bug-fix

#62 Doc and import improvement - guide
  CONTRIBUTING.rst
  docs/api.rst
Labels: status: needs review, affects: documentation

#64 Doc and import improvement #3
  docs/api/index.rst
  docs/api/utils.rst
  docs/file_specification/index.rst
  docs/file_specification/ripple-specs.rst
  docs/index.rst
  docs/interoperability.rst
  docs/supported_formats/hspy.rst
  docs/supported_formats/netcdf.rst
  docs/supported_formats/nexus.rst
  docs/supported_formats/panta_rhei.rst
  docs/supported_formats/phenom.rst
  docs/supported_formats/protochips.rst
  docs/supported_formats/ripple.rst
  docs/supported_formats/usid.rst
  rsciio/__init__.py
  rsciio/netcdf/__init__.py
  rsciio/netcdf/_api.py
  rsciio/nexus/__init__.py
  rsciio/nexus/_api.py
  rsciio/nexus/specifications.yaml
  rsciio/phenom/__init__.py
  rsciio/phenom/_api.py
  rsciio/protochips/__init__.py
  rsciio/protochips/_api.py
  rsciio/prz/__init__.py
  rsciio/prz/_api.py
  rsciio/prz/specifications.yaml
  rsciio/ripple/__init__.py
  rsciio/ripple/_api.py
  rsciio/tests/test_import.py
  rsciio/tests/test_nexus_hdf.py
  rsciio/tests/test_protochips.py
  rsciio/tests/test_ripple.py
  rsciio/utils/__init__.py
  rsciio/utils/hdf5.py
Labels: status: needs review, affects: documentation
