Repository hyperspy/rosettasciio, pull requests merged in 2023-12, with the labels that each got.

#189 Fix reading of dwell time in QuantumDetectors reader
  rsciio/quantumdetector/_api.py
  rsciio/tests/test_quantumdetector.py
  upcoming_changes/189.bugfix.rst
Labels: type: bug, status: needs review, type: bug-fix

#191 Remove usage of deprecated `distutils`
  setup.py
  upcoming_changes/152.maintenance.rst
Labels: type: maintenance

#196 Add keywords to pyproject.toml
  pyproject.toml
Labels: status: needs review

#206 Fix saving hspy file with empty array
  rsciio/_hierarchical.py
  rsciio/hspy/_api.py
  rsciio/tests/test_hspy.py
  upcoming_changes/206.bugfix.rst
Labels: type: bug-fix
