Repository hyperspy/rosettasciio, pull requests merged in 2023-04, with the labels that each got.

#100 Fix bug with python-box 7
  rsciio/digitalmicrograph/_api.py
  rsciio/tests/test_digitalmicrograph.py
  setup.py
  upcoming_changes/100.maintenance.rst
Labels: status: needs review, type: maintenance

#90 Fix exporting scalebar with reciprocal units containing space
  rsciio/image/_api.py
  rsciio/tests/test_image.py
  upcoming_changes/90.bugfix.rst
Labels: status: needs review, type: bug-fix

#98 Updated signal subclassing and metadata of .sur files
  rsciio/digitalsurf/_api.py
  rsciio/tests/test_digitalsurface.py
  upcoming_changes/98.bugfix.rst
  upcoming_changes/98.new.rst
Labels: status: needs review, type: enhancement

#105 cleanup and extend tiff._api
  docs/supported_formats/tiff.rst
  rsciio/tests/test_tiff.py
  rsciio/tests/tiff_files/tiff_Zeiss_SEM.zip
  rsciio/tiff/_api.py
  upcoming_changes/104.new.rst
Labels: status: needs review, type: enhancement

#109 Python 3.11
  .github/workflows/tests.yml
  azure-pipelines.yml
  rsciio/utils/skimage_exposure.py
  setup.py
  upcoming_changes/109.maintenance.rst
Labels: status: needs review, type: maintenance
