Repository hyperspy/rosettasciio, pull requests merged in 2023-08, with the labels that each got.

#149 Add zenodo doi
  docs/index.rst
  upcoming_changes/149.doc.rst
Labels: status: needs review, affects: documentation

#87 Add reader for hamamatsu .img format
  docs/supported_formats/hamamatsu.rst
  docs/supported_formats/index.rst
  docs/supported_formats/supported_formats.rst
  rsciio/hamamatsu/__init__.py
  rsciio/hamamatsu/_api.py
  rsciio/hamamatsu/specifications.yaml
  rsciio/tests/data/hamamatsu/focus_mode.img
  rsciio/tests/data/hamamatsu/operate_mode.img
  rsciio/tests/data/hamamatsu/photon_counting.img
  rsciio/tests/data/hamamatsu/shading_file.img
  rsciio/tests/registry.txt
  rsciio/tests/test_hamamatsu.py
  rsciio/tests/test_jeol.py
  upcoming_changes/87.new.rst
Labels: type: new format

#154 Typo supported formats
  docs/supported_formats/supported_formats.rst
Labels: status: needs review
