Repository hyperspy/rosettasciio, pull requests merged in 2023-11, with the labels that each got.

#174 Mib reader
  docs/conf.py
  docs/supported_formats/index.rst
  docs/supported_formats/quantumdetector.rst
  docs/supported_formats/supported_formats.rst
  rsciio/_docstrings.py
  rsciio/mrc/_api.py
  rsciio/quantumdetector/__init__.py
  rsciio/quantumdetector/_api.py
  rsciio/quantumdetector/specifications.yaml
  rsciio/tests/data/quantumdetector/Merlin_Single_Quad.zip
  rsciio/tests/data/quantumdetector/Merlin_navigation4x2_ROI.zip
  rsciio/tests/registry.txt
  rsciio/tests/test_import.py
  rsciio/tests/test_quantumdetector.py
  upcoming_changes/174.new.rst
Labels: status: needs review, type: new feature

#170 Add option to show progress bar when saving lazy signals to `hspy`/`zspy` files
  rsciio/_hierarchical.py
  rsciio/hspy/_api.py
  rsciio/tests/test_hspy.py
  rsciio/tests/utils/test_rgbtools.py
  rsciio/tvips/_api.py
  rsciio/utils/rgb_tools.py
  rsciio/zspy/_api.py
  upcoming_changes/170.enhancements.rst
Labels: status: needs review, type: enhancement

#182 Fix test suite without optional dependencies
  docs/user_guide/install.rst
  rsciio/emd/_api.py
  rsciio/emd/_emd_ncem.py
  rsciio/emd/_emd_velox.py
  rsciio/jeol/_api.py
  rsciio/tests/test_de5.py
  rsciio/tests/test_emd_ncem.py
  rsciio/tests/test_emd_velox.py
  rsciio/tests/test_import.py
  rsciio/tests/test_jeol.py
  rsciio/tests/test_tvips.py
  rsciio/tvips/_api.py
  rsciio/utils/hdf5.py
  rsciio/utils/tools.py
  upcoming_changes/182.bugfix.rst
Labels: status: needs review

#186 Fix test suite
  .github/workflows/build.yml
  .github/workflows/tests.yml
  rsciio/tests/test_import.py
  upcoming_changes/186.maintenance.rst
Labels: affects: tests, type: maintenance

#173 bugfix: included the "Out" case for the EELS aperture size
  rsciio/pantarhei/_api.py
  rsciio/tests/test_pantarhei.py
  upcoming_changes/173.bugfix.rst
Labels: status: WIP
