Repository hyperspy/rosettasciio, pull requests merged in 2023-05, with the labels that each got.

#112 Recognise both byte and string object for NXdata tag in NeXus reader
  rsciio/nexus/_api.py
  rsciio/tests/nexus_files/nxdata_tagged_as_string.nxs
  rsciio/tests/test_nexus.py
  upcoming_changes/112.enhancements.rst
Labels: type: bug-fix

#114 Tweak pre-commit config to disable `autofix_prs`
  .pre-commit-config.yaml
  .readthedocs.yaml
  CONTRIBUTING.rst
  docs/conf.py
  setup.py
Labels: documentation, status: needs review, type: enhancement

#107 Bugfix for Issue #101 (failing tests after merging #100)
  rsciio/tiff/_api.py
  upcoming_changes/101.bugfix.rst
Labels: status: waiting for author, type: bug-fix

#117 Update dependencies to align with hyperspy
  .github/workflows/tests.yml
  setup.py
Labels: type: maintenance

#125 Clean up packaging
  MANIFEST.in
  pyproject.toml
  rsciio/__init__.py
  rsciio/_version.py
  rsciio/edax/_api.py
  rsciio/msa/_api.py
  rsciio/ripple/_api.py
  rsciio/tests/test_compilers.c
  rsciio/tests/test_mrcz.py
  rsciio/tests/test_usid.py
  rsciio/version.py
  setup.py
  upcoming_changes/125.maintenance.rst
Labels: status: needs review, type: maintenance
