Repository hyperspy/rosettasciio, pull requests merged in 2024-10, with the labels that each got.

#317 Fix loading tiff file lazily
  doc/api/utils.rst
  doc/conf.py
  rsciio/_docstrings.py
  rsciio/tests/test_tiff.py
  rsciio/tiff/_api.py
  rsciio/utils/tools.py
  upcoming_changes/317.bugfix.rst
  upcoming_changes/317.enhancements.rst
Labels: status: needs review

#139 Add delmic load function
  doc/user_guide/supported_formats/delmic.rst
  doc/user_guide/supported_formats/index.rst
  doc/user_guide/supported_formats/supported_formats.rst
  rsciio/delmic/__init__.py
  rsciio/delmic/_api.py
  rsciio/delmic/specifications.yaml
  rsciio/tests/data/delmic/test_hyperspectral.h5
  rsciio/tests/registry.txt
  rsciio/tests/test_delmic.py
  rsciio/tests/test_import.py
  rsciio/tests/test_usid.py
  upcoming_changes/139.new.rst
Labels: status: needs review, type: new format

#327 Fix scale in white field image in renishaw reader
  doc/user_guide/supported_formats/renishaw.rst
  rsciio/tests/test_renishaw.py
  rsciio/utils/image.py
  upcoming_changes/327.bugfix.rst
Labels: type: bug-fix
