Repository hyperspy/rosettasciio, pull requests merged in 2024-07, with the labels that each got.

#280 File_Writer for DigitalSurf files
  doc/user_guide/supported_formats/digitalsurf.rst
  rsciio/digitalsurf/__init__.py
  rsciio/digitalsurf/_api.py
  rsciio/digitalsurf/specifications.yaml
  rsciio/tests/data/digitalsurf/test_RGBSURFACE.sur
  rsciio/tests/registry.txt
  rsciio/tests/test_digitalsurf.py
  rsciio/tests/test_import.py
  upcoming_changes/280.enhancements.rst
Labels: status: waiting for author, type: new feature

#282 Fix test failure in empad test when pyxem >=0.19 is installed
  rsciio/tests/test_empad.py
Labels: status: needs review, type: maintenance

#287 EMD Velox: fix reading EDS stream detector lazily with `sum_EDS_detectors=True`
  rsciio/emd/_emd_velox.py
  rsciio/tests/test_emd_velox.py
  rsciio/utils/fei_stream_readers.py
  upcoming_changes/287.bugfix.rst
Labels: status: needs review, type: bug-fix
